name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - run: npm i
      #- run: |
       #   echo 'module.exports.basePath = "/nextjs-template"' >> next.config.js
      - run: npm run testnet:build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      #- run: npm run export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

     # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
